language: ruby
rvm:
  - 2.5
install:
  - bundle install
  - curl -L -o packer.zip https://releases.hashicorp.com/packer/1.2.2/packer_1.2.2_linux_amd64.zip && unzip -d bin packer.zip
script:
  - PATH=$(pwd)/bin:$PATH bundle exec rake
